export const WIZARD_STEPS = [
  {
    id: 1,
    label: "Tus Datos",
    title: "Empezamos simple",
    message: "Te pido solo lo justo para dejar el turno claro desde el primer intento.",
    chips: ["Contacto claro", "Validación al momento"],
  },
  {
    id: 2,
    label: "El Día",
    title: "Buscamos un buen día",
    message: "Mostramos fechas reales para que elijas con calma y sin vueltas.",
    chips: ["Fechas reales", "Sin perder avances"],
  },
  {
    id: 3,
    label: "Tu Horario",
    title: "Elegís tu horario",
    message: "Ves solo bloques libres para evitar cruces y decidir más rápido.",
    chips: ["Bloques libres", "Sin superposiciones"],
  },
  {
    id: 4,
    label: "Confirmar",
    title: "Listo para confirmar",
    message: "Revisás el resumen y te llevás un código para gestionar cualquier cambio.",
    chips: ["Resumen final", "Código de gestión"],
  },
];

export const BOOKING_SUPPORT_PILLS = [
  "Reserva guiada",
  "WhatsApp como canal principal",
  "Código para gestionar cambios",
];

export const SUBJECT_SUGGESTIONS_BY_LEVEL = {
  Primaria: [
    "Arte",
    "Ciencias Naturales",
    "Ciencias Sociales",
    "Educación Física",
    "Inglés",
    "Lengua y Literatura",
    "Matemática",
    "Música",
  ],
  Secundaria: [
    "Biología",
    "Educación Artística",
    "Educación Ética y Ciudadana",
    "Educación Física",
    "Filosofía",
    "Física",
    "Geografía",
    "Historia",
    "Inglés",
    "Lengua y Literatura",
    "Matemática",
    "Psicología",
    "Química",
  ],
  "Secundaria Tecnica": [
    "Biología",
    "Dibujo Técnico",
    "Educación Física",
    "Electricidad",
    "Electromecánica",
    "Electrónica",
    "Física",
    "Geometría",
    "Historia",
    "Informática",
    "Inglés",
    "Instalaciones",
    "Lengua y Literatura",
    "Matemática",
    "Máquinas",
    "Mecánica",
    "Química",
    "Sistemas Automáticos",
    "Tecnología",
  ],
  Terciario: [
    "Administración General",
    "Antropología Social",
    "Didáctica y Currículo",
    "Filosofía de la Educación",
    "Gestión Educativa",
    "Historia de la Educación",
    "Historia Social Argentina",
    "Informática Educativa",
    "Inglés",
    "Lengua Extranjera",
    "Metodología de la Investigación Educativa",
    "Pedagogía",
    "Política y Legislación Educativa Argentina",
    "Prácticas Docentes",
    "Psicología de la Educación",
    "Sociología",
    "Sociología de la Educación",
    "Tecnología Educativa",
  ],
  Universitario: [
    "Administración de Empresas",
    "Álgebra",
    "Álgebra Lineal",
    "Análisis Matemático",
    "Antropología",
    "Biología Celular",
    "Cálculo",
    "Contabilidad",
    "Derecho Constitucional",
    "Derecho Penal",
    "Economía",
    "Estadística",
    "Filosofía",
    "Física",
    "Física General",
    "Fisiología",
    "Geografía",
    "Gestión de Proyectos",
    "Historia",
    "Historia Argentina",
    "Inglés",
    "Inglés Técnico",
    "Introducción a la Administración",
    "Introducción a la Informática",
    "Legislación Laboral",
    "Lógica",
    "Matemática",
    "Matemática Discreta",
    "Metodología de la Investigación",
    "Microeconomía",
    "Programación",
    "Psicología",
    "Química",
    "Química General",
    "Química Orgánica",
    "Sociología",
    "Sistemas de Información",
    "Termodinámica",
    "Trigonometría",
  ],
};

export const getSubjectSuggestions = (educationLevel) =>
  SUBJECT_SUGGESTIONS_BY_LEVEL[educationLevel] ?? [];
